// src/services/auth.js
// ============================================
// AUTH SERVICE - WITH GOOGLE LOGIN SUPPORT
// ============================================
// This service handles all authentication operations:
// - Mock user database (localStorage)
// - Email/Password login and registration
// - Google OAuth token handling
// - JWT token generation and verification
// - User profile updates
// - Password changes

import { jwtDecode } from 'jwt-decode';

// ============================================
// 1. MOCK USER DATABASE
// ============================================
// Users are stored in localStorage for persistence
// In a real app, this would be a database on a server

let users = [];

// Load users from localStorage
const loadUsers = () => {
  try {
    const saved = localStorage.getItem('auth_users');
    if (saved) {
      users = JSON.parse(saved);
    } else {
      // Seed with a test user if no users exist
      users = [
        {
          id: '1',
          name: 'Test User',
          email: 'test@example.com',
          password: 'password123',
          createdAt: new Date().toISOString()
        }
      ];
      localStorage.setItem('auth_users', JSON.stringify(users));
    }
  } catch (error) {
    console.error('Error loading users:', error);
    users = [];
  }
};

// Save users to localStorage
const saveUsers = () => {
  try {
    localStorage.setItem('auth_users', JSON.stringify(users));
  } catch (error) {
    console.error('Error saving users:', error);
  }
};

// Load users on initialization
loadUsers();

// ============================================
// 2. JWT TOKEN HELPERS
// ============================================
// Generate a fake JWT token for our mock auth
// In a real app, this would be generated by the server

const generateToken = (user) => {
  const payload = {
    id: user.id,
    email: user.email,
    name: user.name,
    exp: Date.now() + 7 * 24 * 60 * 60 * 1000 // 7 days expiry
  };
  return btoa(JSON.stringify(payload));
};

// Verify a mock JWT token
export const verifyToken = (token) => {
  try {
    const payload = JSON.parse(atob(token));
    if (payload.exp < Date.now()) {
      return null;
    }
    return payload;
  } catch (error) {
    return null;
  }
};

// ============================================
// 3. EMAIL/PASSWORD AUTH
// ============================================

// Login with email and password
export const loginUser = async (email, password) => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 800));

  // Validate inputs
  if (!email || !password) {
    throw new Error('Email and password are required');
  }

  // Find user by email
  const user = users.find(u => u.email.toLowerCase() === email.toLowerCase());
  
  if (!user) {
    throw new Error('Invalid email or password');
  }

  // Check password (in real app, this would use bcrypt compare)
  if (user.password !== password) {
    throw new Error('Invalid email or password');
  }

  // Generate token and return user data (excluding password)
  const token = generateToken(user);
  const { password: _, ...userWithoutPassword } = user;
  return {
    user: userWithoutPassword,
    token
  };
};

// Register a new user with email and password
export const registerUser = async (name, email, password) => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 800));

  // Validate inputs
  if (!name || !email || !password) {
    throw new Error('All fields are required');
  }

  if (password.length < 6) {
    throw new Error('Password must be at least 6 characters');
  }

  // Check if user already exists
  if (users.some(u => u.email.toLowerCase() === email.toLowerCase())) {
    throw new Error('A user with this email already exists');
  }

  // Create new user
  const newUser = {
    id: Date.now().toString(),
    name: name.trim(),
    email: email.trim().toLowerCase(),
    password,
    createdAt: new Date().toISOString()
  };

  users.push(newUser);
  saveUsers();

  // Generate token and return user data (excluding password)
  const token = generateToken(newUser);
  const { password: _, ...userWithoutPassword } = newUser;
  return {
    user: userWithoutPassword,
    token
  };
};

// ============================================
// 4. GOOGLE OAUTH SUPPORT
// ============================================

// ✅ Verify Google token
// Google tokens are already verified by the @react-oauth/google library
// This function is for additional validation if needed
export const verifyGoogleToken = async (token) => {
  try {
    // Decode the token to check if it's valid
    const decoded = jwtDecode(token);
    
    // Check if it has required Google fields
    if (!decoded.sub || !decoded.email) {
      throw new Error('Invalid Google token: missing required fields');
    }
    
    // Optional: Verify with Google's tokeninfo endpoint
    // const response = await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${token}`);
    // const data = await response.json();
    // if (!data.email) throw new Error('Invalid token');
    
    return { success: true, userData: decoded };
  } catch (error) {
    console.error('Google token verification failed:', error);
    throw new Error('Invalid Google token');
  }
};

// ============================================
// 5. SESSION MANAGEMENT
// ============================================

// Get current user from token (supports both mock and Google tokens)
export const getCurrentUser = async (token) => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 300));

  if (!token) {
    throw new Error('No token provided');
  }

  // ===== Try Google Token =====
  try {
    const decoded = jwtDecode(token);
    // Check if it's a Google token (has 'sub' field)
    if (decoded.sub && decoded.email) {
      // Check if this Google user exists in our mock database
      // If not, create a new user entry
      let existingUser = users.find(u => u.email.toLowerCase() === decoded.email.toLowerCase());
      
      if (!existingUser) {
        // Create a new user for this Google account
        const newUser = {
          id: `google_${decoded.sub}`,
          name: decoded.name || decoded.given_name || 'Google User',
          email: decoded.email,
          picture: decoded.picture || null,
          provider: 'google',
          createdAt: new Date().toISOString()
        };
        users.push(newUser);
        saveUsers();
        existingUser = newUser;
      }
      
      // Return user data
      const { password: _, ...userWithoutPassword } = existingUser;
      return {
        ...userWithoutPassword,
        picture: decoded.picture || userWithoutPassword.picture || null,
      };
    }
  } catch {
    // Not a Google token, continue to mock token check
  }

  // ===== Try Mock Token =====
  const payload = verifyToken(token);
  if (!payload) {
    throw new Error('Invalid or expired token');
  }

  const user = users.find(u => u.id === payload.id);
  if (!user) {
    throw new Error('User not found');
  }

  const { password: _, ...userWithoutPassword } = user;
  return userWithoutPassword;
};

// ============================================
// 6. USER PROFILE MANAGEMENT
// ============================================

// Update user profile
export const updateUserProfile = async (userId, updates) => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));

  const userIndex = users.findIndex(u => u.id === userId);
  if (userIndex === -1) {
    throw new Error('User not found');
  }

  // Prevent updating certain fields
  const allowedUpdates = ['name', 'email', 'picture'];
  const filteredUpdates = {};
  for (const key of allowedUpdates) {
    if (updates[key] !== undefined) {
      filteredUpdates[key] = updates[key];
    }
  }

  // Update user data
  users[userIndex] = {
    ...users[userIndex],
    ...filteredUpdates,
  };

  saveUsers();

  // Return updated user without password
  const { password: _, ...userWithoutPassword } = users[userIndex];
  return userWithoutPassword;
};

// Change password
export const changePassword = async (userId, currentPassword, newPassword) => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));

  const userIndex = users.findIndex(u => u.id === userId);
  if (userIndex === -1) {
    throw new Error('User not found');
  }

  // Check if user has a password (Google users may not)
  if (!users[userIndex].password) {
    throw new Error('This account uses Google login. Please use Google to sign in.');
  }

  // Verify current password
  if (users[userIndex].password !== currentPassword) {
    throw new Error('Current password is incorrect');
  }

  // Validate new password
  if (newPassword.length < 6) {
    throw new Error('New password must be at least 6 characters');
  }

  // Update password
  users[userIndex].password = newPassword;
  saveUsers();

  return { success: true };
};

// ============================================
// 7. LOGOUT (client-side only)
// ============================================

export const logoutUser = () => {
  // Nothing to do on server-side for mock API
  // Client should clear token from localStorage
  return { success: true };
};

// ============================================
// 8. EXPOSE FOR DEBUGGING (optional)
// ============================================

// Get all users (for debugging - remove in production)
export const getAllUsers = () => {
  return users.map(({ password, ...user }) => user);
};

// Clear all users (for testing)
export const clearAllUsers = () => {
  users = [];
  localStorage.removeItem('auth_users');
  loadUsers(); // Reload with seeded user
};